language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.7.0

matrix:
  allow_failures:
    # currently gives StackOverflows in the mailer patch. JRuby bug?
    # possibly https://github.com/jruby/jruby/issues/3193
    - rvm: jruby-9.1.7.0
  exclude:
    - rvm: 2.4.0
      env: REDMINE_VER=2.6-stable
    - rvm: 2.4.0
      env: REDMINE_VER=3.3-stable

branches:
  only:
    - master

addons:
  postgresql: "9.4"

env:
  - REDMINE_VER=2.6-stable
  - REDMINE_VER=3.3-stable
  - REDMINE_VER=master

install: "echo skip bundle install"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create extension unaccent;' -U postgres travis_ci_test

script:
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_pushover
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - mkdir $TESTSPACE
  - cp test/support/* $TESTSPACE/
  - bash -x ./travis.sh
